---
# This file should be put in $HOME/ directory
# Config your default settings here
# If you don't specify command line options, the software will use these default settings 
defaults:
  # emailListFile stores target email address to be notified
  # if you don't specify the email address option in command line, this default setting will be used
  emailListFile: emailListFile
  # slackListFile stores target slack IDs(channel IDs or user IDs) to be notified
  # Only the IDs belonging to your group are available
  # You can find all channel IDs or user IDs using your slack token 
  # if you don't specify the slack IDs option in command line, this default setting will be used
  slackListFile: slackListFile
  # default notification subject(title)
  # being used if no subject option is specified in command line
  subject: New Notification
  # defautification message
  # Only if no message option is specified in command line and default messageFile is not available
  # will this default setting be used by the software
  message: new message
  # default notification message file
  # if no message option is specified in command line, this default messageFile will be used
  # and message will be read from it.
  # if this file is not available, the software will use the above "message" setting
  messageFile: error.log
...
