---
# This config file should be put in $HOME/ directory
# This config file will be extended after more notifiers are addded
notifiers:
  # email notifier config
  smtpemailnotifier:
    # don't change the "type"
    type: smtpemail
    # state "on"/"true" makes email notification valid, while state "off"/"false" makes it invalid
    state: on
    # write your email address that sends the notification email
    account: --------@gmail.com
    # write your email password
    pwd: ------
    # your email host and port
    SMTPHost: smtp.gmail.com
    SMTPPort: 465
    # slack notifier config
  slacknotifier:
    # don't change the "type"
    type: slack
    # state "on"/"true" makes slack notification valid, while state "off"/"false" makes it invalid
    state: on
    # write your slack token(you can get it from
    # https://api.slack.com/custom-integrations/legacy-tokens)
    token: -----------
    # whether you want to send notification as yourself
    asUser: off
    # if asUser is false, you will send notification as a robot
    # specify robot userName and iconEmoji that you prefer
    userName: Notification Robot
    iconEmoji: scream_cat
...
